name: Bug report
description: 创建报告以帮助我们改进
title: "[Bug]"
labels:
  - bug
assignees: Mister-Hope
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 清单
      description: |-
        请确保遵循这些声明。（否则作者可能会把Fxxx的话扔给你）
      options:
        - label: 我正在使用 Node.js 的 **LTS** 版本。
          required: true

        - label: 我正在使用 **最新的 v2 版本** 的 VuePress 和 VuePress 官方插件。
          required: true

        - label: 我正在使用 **最新的 v2 版本** 的 vuepress-theme-hope 和这个存储库中的所有插件。
          required: true

        - label: 我正在遵循文档，并且确定我使用的是正确的配置。
          required: true

        - label: 我已搜索 [FAQ](https://theme-hope.vuejs.press/faq/)
          required: true

  - type: input
    id: package
    attributes:
      label: Package name
      description: 您报告的是哪个包裹
      value: vuepress-theme-hope
      placeholder: package name
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: 您使用的是哪种操作系统?
      description: 您可以选择多个。如果与环境无关，请不要选择任何内容。
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: markdown
    attributes:
      value: |
        ## Describe the bug

        > 如果适用，请添加屏幕截图和日志以帮助解释您的问题。

  - type: textarea
    id: description
    attributes:
      label: 描述错误
      description: 对错误是什么的清晰简洁的描述。
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他上下文
      description: 如果您没有报告明显的东西，则需要最小的复制存储库和相关日志。
      placeholder: 在此处添加有关该问题的任何其他上下文。特别是问题发生在某些操作系统，浏览器或配置中。
